/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package principal;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JRException;
import report.ClassPeliculaRentada;
import report.ClassPeliculaRetrazada;
import utilities.DBSql;
import utilities.ResultsetTable;

/**
 *
 * @author LCRT
 */
public class JdVerTodasPeliculasRentadas extends javax.swing.JDialog {
 DBSql sql = null;
    /**
     * Creates new form JdPeliculaRentadas
     */
    public JdVerTodasPeliculasRentadas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
           sql = new DBSql();
        populatePelRen();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeliculasRentadas = new javax.swing.JTable();
        lblInfo = new javax.swing.JLabel();
        btnImpTodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PELICULAS RENTADAS");

        tblPeliculasRentadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPeliculasRentadas);

        lblInfo.setText("jLabel1");

        btnImpTodo.setText("IMPRIMIR TODAS LA PELICULAS RENTADAS");
        btnImpTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInfo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnImpTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(lblInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnImpTodo)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImpTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpTodoActionPerformed
        // TODO add your handling code here:

        if (tblPeliculasRentadas.getRowCount()<=0) {

            JOptionPane.showMessageDialog(this,"No hay Peliculas Rentadas");
        }else{
        
           ClassPeliculaRentada   pr=new ClassPeliculaRentada();
           this.dispose();
            try {
                pr.generarReporte();
            } catch (JRException ex) {
                Logger.getLogger(JdVerTodasPeliculasRentadas.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(JdVerTodasPeliculasRentadas.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        }

    }//GEN-LAST:event_btnImpTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdVerTodasPeliculasRentadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdVerTodasPeliculasRentadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdVerTodasPeliculasRentadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdVerTodasPeliculasRentadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JdVerTodasPeliculasRentadas dialog = new JdVerTodasPeliculasRentadas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImpTodo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JTable tblPeliculasRentadas;
    // End of variables declaration//GEN-END:variables

    private void populatePelRen() {

    String sqlPelRen="SELECT detren.coddetren,detren.codren,pel.titpel,pel.codpel,pelco.numcopia,ren.codcli,detren.entregada,pelco.codestado FROM  tb_detalle_renta detren\n" +
"INNER JOIN tbpelicula_copia pelco ON detren.codpel=pelco.codpel AND detren.numcopia=pelco.numcopia\n" +
"INNER JOIN tbpelicula pel ON pel.codpel=pelco.codpel\n" +
"INNER JOIN  tbrenta ren ON ren.codren=detren.codren\n" +
"WHERE detren.entregada=0 AND pelco.codestado=2";
    

        ResultSet rs = sql.displaytb(sqlPelRen);

        ResultsetTable rst = new ResultsetTable();
        tblPeliculasRentadas.remove(this);
        try {

            tblPeliculasRentadas.setModel(rst.rstomodel(rs));
            lblInfo.setText("Ctd : " + tblPeliculasRentadas.getRowCount());


        } catch (SQLException ex) {
            Logger.getLogger(JdVerTodasPeliculasRentadas.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

    }

}
